# Generated by Django 4.0.4 on 2022-05-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='Имя пользователя')),
                ('firstname', models.CharField(max_length=64, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='Электронная почта')),
                ('birthday_year', models.PositiveIntegerField()),
            ],
        ),
    ]
