# Generated by Django 4.0.4 on 2022-05-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_firstname_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday_year',
            field=models.PositiveIntegerField(null=True, verbose_name='Год рождения'),
        ),
    ]
